# Generated by Django 5.1.15 on 2026-06-13 14:46

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('gross_sales', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('refunds', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('cogs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('operating_expenses', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('net_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('transactions', models.PositiveIntegerField(default=0)),
                ('inventory_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='branches.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['organization', 'branch', '-snapshot_date'], name='analytics_m_organiz_5d04cd_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'branch', 'snapshot_date'), name='uniq_snapshot_branch_day')],
            },
        ),
    ]
